import { useEffect } from 'react'

import Head from 'next/head'
import { useRouter } from 'next/router'

import { useSelector } from 'react-redux'
import GuestPage from './guest'
import HomePage from './home'

export default function Home() {
    const user = useSelector((state) => state.AuthReducer.authData)
    const router = useRouter()

    useEffect(() => {
        user ? router.push('/home') : router.push('/login')
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>

    )

    // // Guest
    // function Guest() {
    //     return (
    //         <GuestPage />
    //     )
    // }

    // // Authorize User
    // function User() {
    //     return (
    //         <HomePage />
    //     )
    // }

}